<a href="https://colab.research.google.com/github/coderanandmaurya/AI-LOGIC/blob/main/Fuzzyset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Union of Two Fuzzy Sets
A = dict()
B = dict()
Y = dict()
  
A = {"a": 0.2, "b": 0.3, "c": 0.6, "d": 0.6}
B = {"a": 0.9, "b": 0.9, "c": 0.4, "d": 0.5}
  
print('The First Fuzzy Set is :', A)
print('The Second Fuzzy Set is :', B)
  
  
for A_key, B_key in zip(A, B):
    A_value = A[A_key]
    B_value = B[B_key]
  
    if A_value > B_value:
        Y[A_key] = A_value
    else:
        Y[B_key] = B_value
     
print('Fuzzy Set Union is :', Y)

The First Fuzzy Set is : {'a': 0.2, 'b': 0.3, 'c': 0.6, 'd': 0.6}
The Second Fuzzy Set is : {'a': 0.9, 'b': 0.9, 'c': 0.4, 'd': 0.5}
Fuzzy Set Union is : {'a': 0.9, 'b': 0.9, 'c': 0.6, 'd': 0.6}


In [2]:
# Intersection of Two Fuzzy Sets
A = dict()
B = dict()
Y = dict()
  
A = {"a": 0.2, "b": 0.3, "c": 0.6, "d": 0.6}
B = {"a": 0.9, "b": 0.9, "c": 0.4, "d": 0.5}
  
print('The First Fuzzy Set is :', A)
print('The Second Fuzzy Set is :', B)
  
  
for A_key, B_key in zip(A, B):
    A_value = A[A_key]
    B_value = B[B_key]
  
    if A_value < B_value:
        Y[A_key] = A_value
    else:
        Y[B_key] = B_value
print('Fuzzy Set Intersection is :', Y)

The First Fuzzy Set is : {'a': 0.2, 'b': 0.3, 'c': 0.6, 'd': 0.6}
The Second Fuzzy Set is : {'a': 0.9, 'b': 0.9, 'c': 0.4, 'd': 0.5}
Fuzzy Set Intersection is : {'a': 0.2, 'b': 0.3, 'c': 0.4, 'd': 0.5}


In [3]:
# Difference Between Two Fuzzy Sets
A = dict()
Y = dict()
  
A = {"a": 0.2, "b": 0.3, "c": 0.6, "d": 0.6}
  
print('The Fuzzy Set is :', A)
  
  
for A_key in A:
   Y[A_key]= 1-A[A_key]
          
print('Fuzzy Set Complement is :', Y)

The Fuzzy Set is : {'a': 0.2, 'b': 0.3, 'c': 0.6, 'd': 0.6}
Fuzzy Set Complement is : {'a': 0.8, 'b': 0.7, 'c': 0.4, 'd': 0.4}


In [4]:
# Difference Between Two Fuzzy Sets
A = dict()
B = dict()
Y = dict()
  
A = {"a": 0.2, "b": 0.3, "c": 0.6, "d": 0.6}
B = {"a": 0.9, "b": 0.9, "c": 0.4, "d": 0.5}
  
print('The First Fuzzy Set is :', A)
print('The Second Fuzzy Set is :', B)
    
for A_key, B_key in zip(A, B):
    A_value = A[A_key]
    B_value = B[B_key]
    B_value = 1 - B_value
  
    if A_value < B_value:
        Y[A_key] = A_value
    else:
        Y[B_key] = B_value
          
print('Fuzzy Set Difference is :', Y)

The First Fuzzy Set is : {'a': 0.2, 'b': 0.3, 'c': 0.6, 'd': 0.6}
The Second Fuzzy Set is : {'a': 0.9, 'b': 0.9, 'c': 0.4, 'd': 0.5}
Fuzzy Set Difference is : {'a': 0.09999999999999998, 'b': 0.09999999999999998, 'c': 0.6, 'd': 0.5}


In [24]:
pip install scikit-fuzzy

In [31]:
"""import skfuzzy as fuzz
def convert_dict(A,B):
    A_x,A_mfx,B_x,B_mfx = [],[],[],[]
    for key in A:
        A_x.append(key)
        A_mfx.append(A[key])
    for key in B:
        B_x.append(key)
        B_mfx.append(B[key])
    return np.array(A_x),np.array(A_mfx),np.array(B_x),np.array(B_mfx)
def main(): 
   
    while True:
        print("Menu Driven Program")
        print("1.Cartesian product")
        print("2.Exit")
        choice=int(input("Enter your choice:"))
        if choice==1:
            A_x, A_mfx, B_x, B_mfx=convert_dict(d,d1)
            cartesian_product = fuzz.cartprod(A_mfx, B_mfx)
            print("\nCartesian product:", cartesian_product, sep="\n")
        
        elif choice==2:
            break
        else:
            print("Wrong choice")
  
if __name__ == "__main__": 
    print("----------------------"+
        "FUZZY SET OPERATIONS"+ 
        "----------------------")
    n = int(input("enter  no.of elements of set 1:"))
    d = {}
    for i in range(n):
        keys = input() 
        values = float(input())
        d[keys] = values
    n1 = int(input("enter  no.of elements of set 2:"))
    d1 = {}
    for i in range(n1):
        keys1 = input() 
        values1 = float(input())
        d1[keys1] = values1
  
main() """

'import skfuzzy as fuzz\ndef convert_dict(A,B):\n    A_x,A_mfx,B_x,B_mfx = [],[],[],[]\n    for key in A:\n        A_x.append(key)\n        A_mfx.append(A[key])\n    for key in B:\n        B_x.append(key)\n        B_mfx.append(B[key])\n    return np.array(A_x),np.array(A_mfx),np.array(B_x),np.array(B_mfx)\ndef main(): \n   \n    while True:\n        print("Menu Driven Program")\n        print("1.Cartesian product")\n        print("2.Exit")\n        choice=int(input("Enter your choice:"))\n        if choice==1:\n            A_x, A_mfx, B_x, B_mfx=convert_dict(d,d1)\n            cartesian_product = fuzz.cartprod(A_mfx, B_mfx)\n            print("\nCartesian product:", cartesian_product, sep="\n")\n        \n        elif choice==2:\n            break\n        else:\n            print("Wrong choice")\n  \nif __name__ == "__main__": \n    print("----------------------"+\n        "FUZZY SET OPERATIONS"+ \n        "----------------------")\n    n = int(input("enter  no.of elements of set 1:")

In [30]:
import numpy as np

# Max-Min Composition given by Zadeh
def maxMin(x, y):
    z = []
    for x1 in x:
        for y1 in y.T:
            z.append(max(np.minimum(x1, y1)))
    return np.array(z).reshape((x.shape[0], y.shape[1]))

# Max-Product Composition given by Rosenfeld
def maxProduct(x, y):
    z = []
    for x1 in x:
        for y1 in y.T:
            z.append(max(np.multiply(x1, y1)))
    return np.array(z).reshape((x.shape[0], y.shape[1]))

# 3 arrays for the example
r1 = np.array([[1, 0, .7], [.3, .2, 0], [0, .5, 1]])
r2 = np.array([[.6, .6, 0], [0, .6, .1], [0, .1, 0]])
r3 = np.array([[1, 0, .7], [0, 1, 0], [.7, 0, 1]])

print("R1oR2 => Max-Min : \n" + str(maxMin(r1, r2)) + "\n")
print("R1oR3 => Max-Min : \n" + str(maxMin(r1, r3)) + "\n")
print("R1oR3 => Max-Product : \n" + str(maxProduct(r1, r3)) + "\n\n")

print("R1oR2oR3 => Max-Min : \n" + str(maxMin(r1, maxMin(r2, r3))) + "\n")
print("R1oR2oR3 => Max-Product : \n" + str(maxProduct(r1, maxProduct(r2, r3))) + "\n\n")

R1oR2 => Max-Min : 
[[0.6 0.6 0. ]
 [0.3 0.3 0.1]
 [0.  0.5 0.1]]

R1oR3 => Max-Min : 
[[1.  0.  0.7]
 [0.3 0.2 0.3]
 [0.7 0.5 1. ]]

R1oR3 => Max-Product : 
[[1.   0.   0.7 ]
 [0.3  0.2  0.21]
 [0.7  0.5  1.  ]]


R1oR2oR3 => Max-Min : 
[[0.6 0.6 0.6]
 [0.3 0.3 0.3]
 [0.1 0.5 0.1]]

R1oR2oR3 => Max-Product : 
[[0.6   0.6   0.42 ]
 [0.18  0.18  0.126]
 [0.035 0.3   0.05 ]]


